### ISSUE TITLE
Repository management

### ISSUE THREAD

**Issue by choomz** [Kitano/KitanoConnectionBundle#10]
Je propose une implémentation des repositories via le compiler pass : 
https://github.com/Kitano/KitanoConnectionBundle/blob/repository/Resources/config/services.xml

Avec pour config : 
https://gist.github.com/choomz/55516610dd7d2cab2a28

Il est clair qu'ici nous enregistrons dans le container l'ensemble des repositories taggués (par notre bundle et par les potentiels utilisateurs) pour au final n'en utiliser qu'un seul.

Ca à l'avantage de ne pas influer sur le chargement des bundles dans le kernel.

L'autre solution est d'utiliser directement l'id du service souhaité pour le repository (sans le compiler pass donc) : 
https://gist.github.com/choomz/5c6695640c11caccda96

Ca a l'avantage de ne pas stocker les éventuels repositories dans le container, par contre, ça oblige à respecter un ordre de chargement des bundles dans le kernel.

Dans les deux cas, ça regle le soucis d'implémentation d'un repo/connection custom.
Si l'utilisateur veut se débarasser du proxy, il peut.

A noter que toutes les entrées seront définies avec des valeurs par défault dans l'extension. Ce sont juste possibilité de surcharges par l'utilisateur.

Ah, et il faut ajouter un ConnectionInterface.

Vos avis ?

**Comment by benjamindulau** [comment]
J'ai crée l'interface `ConnectionInterface` dans la branche master.

**Comment by choomz** [comment]
Je ferme suite à b97e12a2e61b2ad3ed7d9ac74708a8ccc0550b0a
