### ISSUE TITLE
Utilisations des filtres

### ISSUE THREAD

**Issue by armetiz** [Kitano/KitanoConnectionBundle#12]
L'utilisation des filtres pour passer un peu tout me semble mal designé..

Est-ce que l'utilisation d'un simple Array pour ces "options" est approprié face à un Objet typé ?
Doit-on mettre le "type" de la connexion, ainsi que le "status" et la "depth" que l'on souhaite dans un tableau d'option ? 
Doit-on autoriser l'ajout d'autre option à la volé ?

**Comment by choomz** [comment]
1. L'array était une simple approche, étant donné qu'on avait que 3 critères.
2. Je pense que oui
3. On en a besoin pour le moment ? :D

**Comment by armetiz** [comment]
En fait, ce qui est étrange à l'utilisation c'est ce genre de cas :

``` php
$manager->areConnected($objA, $objB, array('status' => ConnectionInterface::STATUS_CONNECTED));
```

On peux tout simplement ignorer des options dans certains cas.. Mais.. ca me choc un peu à l'utilisation.

**Comment by benjamindulau** [comment]
J'avoue que je ne comprend pas trop la question, qu'est-ce qui te choque là dedans:

``` PHP
$manager->areConnected($objA, $objB, array('status' => ConnectionInterface::STATUS_CONNECTED));
```

?

**Comment by armetiz** [comment]
En gros, cette fonction c'est "Est-ce que les objets sont connectés entre eux avec le status connecté ?"
C'est un peu comme si je te demandais "Est-ce que cette fille blonde est blonde ?"

Comme je le disais, ce n'est en effet pas grave, en ce sens où les repositories peuvent ignorer certains filtres en fonction des methodes appelés.
Mais si je suis le seul choqué, on ferme et on voit à l'utilisation futur.

**Comment by benjamindulau** [comment]
Oook, j'avais pas vu cette subilité, effectivement c'est bizarre.
Quelle autre solution avons-nous pour pallier à ce type de problème ?

En fait ce status est un peu particulier, l'idée est de conserver une trace d'une connection après qu'elle ait été déconnectée. Dans ce cas je ne sais pas s'il ne vaut mieux pas ajouter une méthode du type "wereConnected()" ou un truc du genre.

Enfin là on rentre dans le détail, comment pouvons-nous autoriser que certaines valeurs ? Faut-il lâcher une exception si une option non valide est passée ? ou faut-il simplement l'ignorer (actuellement c'est ce qu'on fait)  ?

Je crois qu'il n'y a pas vraiment de bonne solution, seulement un choix à faire :)
Nous avons le temps jusqu'à une première version stable pour changer d'avis et modifier l'interface.
Je pense que la solution actuelle est convenable, nous pouvons attendre jusqu'à trouver des cas où ça nous gène vraiment à l'utilisation.

**Comment by armetiz** [comment]
En fait, ce qui est étrange, c'est peut-être le choix du nom que l'on a fait.
Nous avons une Connection qui peut être connecté ou déconnecté.. "Une connexion déconnecté.." Rien que là, c'est un peu à la limite de l'étrange.

``` php
$manager->areConnected($objA, $objB);
```

D'ailleurs, cette méthode, doit-elle retourner "vrai" uniquement si les deux objets ont une connection avec le status "Connecté" ?
A noter, que cette méthode sert actuellement à d'autres méthodes du ConnectionManager pour vérifier l'existence de connection avant d'en créer ou détruire une..

Si l'on considere que areConnected doit retourner vrai s'il existe une Connection entre deux NodeInterface, quelque soit les propriétés de cette Connection.. Alors

``` php
$nodeA = new Node();
$nodeB = new Node();
$connection = $manager->create($nodeA, $nodeB);
$manager->disconnect($connection);
$manager->areConnected($nodeA, $nodeB); //true

$connection = $manager->create($nodeA, $nodeB); //throw AlreadyConnectedException
```

En fait, bien que je comprenne l'intérêt de garder un "status" sur une Connection à des fins d'historique.. Je pense que ca fou la grouille pas mal.
Hormis le soucis que l'on évoque dans cette Issue, cela a posé aussi un soucis sur le choix du nom de la méthode:

``` php
$manager->create(NodeInterface $nodeA, NodeInterface $nodeB);
$manager->connect(ConnectionInterface $connection);
```

Si l'on supprime le 'status' dans une Connection, on peux supprimer la méthode create / destroy, et utiliser connect / disconnect en lieu et place. Ce qui est bien plus logique à mon avis.

``` php
//Exemple de changement d'interface
$nodeA = new Node();
$nodeB = new Node();

$manager->connect($nodeA, nodeB); //Create a new connection between to node
```

**Comment by benjamindulau** [comment]
+1 pour moi

Maintenant je pense qu'il faut quand même réfléchir à une manière de conserver les connections "déconnectées". Peut-être que l'utilisation d'un status n'est effectivement pas la bonne solution.

Des idées ?

**Comment by armetiz** [comment]
On peux imaginer un système d'historique annexe, mais ca fait un peu overhead :/
Quel est intérêt de conserver l'état de déconnection ? @choomz t'en penses quoi ?

Mon avis, c'est que cette information ne doit pas être géré par le ConnectionBundle mais par un Logger externe. Et grace au Event, libre à l'application de conserver cette information ou non..
Car au final, conserver le status de déconnection, ca s'approche d'un - petit - système de versionning.. Ce n'est pas un peu hors sujet ?

**Comment by choomz** [comment]
+1 pour moi aussi.

Pour les historiques, pourquoi ne pas faire une méthode hasHistory ou wereConnected comme disait armetiz qui permettrait de retrouver l'historique de deux connections (si on part du principe qu'une connection possède un datetime, puis a été déconnecté (autre datetime) puis éventuellement reconnecté, l'history serait plus un tableau d'interactions entre deux NodeInterface.

Ça permet de dissocier complétement les manipulations des connections & les infos relatives à ces mêmes connections.

Du coup les status ne seraient remontés que pour les demandes d'historiques, et on les supprime des filtres servant à gérer les interactions.

**Comment by choomz** [comment]
Ah ben, on a posté en même temps.

A voir si c'est trop lourd ou pas oui effectivement.

**Comment by armetiz** [comment]
KISS : Il y a dedans le "Simple" :p
Du coups, est-ce que l'historique d'une Connexion est une donnée nécessaire ? C'est à mon avis la 1° question à ce poser.

**Comment by choomz** [comment]
Je n'ai pas de cas d'utilisation pour le moment. Mais comme disait Benjamin, ça pourrait être utile ... (stats etc ..).

**Comment by choomz** [comment]
Par contre, effectivement logguer toutes les interactions des connections, ça risque de grossir très vite.

**Comment by armetiz** [comment]
Après discussion IRC, on supprime le status des Connections.
