### ISSUE TITLE
Dependances librairies externes

### ISSUE THREAD

**Issue by armetiz** [Kitano/KitanoConnectionBundle#15]
La branch master a actuellement en dépendance :
- symfony/framework-bundle
- symfony/validator
- doctrine/common

La question se pose surtout sur le Symfony/Validator qui est utilisé actuellement pour valider les Filtres. Il est possible de valider les filtres à la main et sans utiliser ce composant, sachant qu'actuellement le nombre de donnée qu'un filtre peux contenir est assez faible.

**Comment by choomz** [comment]
Vu ce que tu as fais au niveau du filter validator (qui est nettement plus lisible), j'aurais tendance à dire qu'on peut garder le validator. On a déja le framework bundle, on peut estimer que l'utilisateur possède déja le validator.

**Comment by armetiz** [comment]
Je pense aussi oui.

**Comment by benjamindulau** [comment]
+1 pour le validateur, autant l'utiliser !
