### ISSUE TITLE
Doctrine pre remove listener

### ISSUE THREAD

**Issue by choomz** [Kitano/KitanoConnectionBundle#17]
Actuellement il y a un listener sur le preRemove doctrine.

J'ai un peu de mal à cerner son utilité étant donné que la connection est supprimée par le repository.

Le code du listener actuel fait un getConnections sur un $entity, hors nous sommes dans le life cycle de Connection (entity est donc une connection qui va être supprimée).

De plus le container est injecté, et on m'a soufflé qu'il ne fallait pas :)

Si nous étions dans un contexte ou $entity était un user,ou autre chose, alors on ne voudrait pas forcement supprimer toutes les connections de cet utilisateur lors de la suppression d'un like par exemple.

Bref, si il n'est plus d'actualité, je pensais le supprimer ? Sinon je veux bien plus d'infos.

**Comment by armetiz** [comment]
Ce listener a l'intérêt de supprimer les Connection liées à un Node que l'on supprime.
L'utilisateur qui a créé une Connection entre UserNoder & PhotoNode ne réalisera pas forcement la suppression de la Connection lorsqu'il supprimera le UserNode.
De plus, si on récupère la connection à partir de PhotoNode on tombera sur une source UserNode qui sera vide.. 

Si on ne doit pas supprimer les connections lorsque l'on supprime les Node, il faut être conscient que l'on peut avoir pléthore de Connection orpheline.

Personnellement, je souhaite que le ConnectionBundle s'occupe de supprimer tout seul les Connection lorsque l'on supprime un des Node rattaché.
Ca peut-être une option de configuration..

**Comment by choomz** [comment]
Ok, j'ai fais un mic mac dans mon cerveau hier soir, effectivement ... Je rajoute un test par contre sur le type de l'entity

**Comment by armetiz** [comment]
Ah j'aurai juré avoir placé un test sur l'entité.. 

PS : Pour l'injection du Container, c'est la seule solution que j'ai trouvé. Si on injecte uniquement le connectionManager, on se retrouve avec une erreur "injection cyclique" :p C'est ouvert à toute critique et solution ! :dancers:
