### ISSUE TITLE
Modification de disconnect() du Manager

### ISSUE THREAD

**Issue by choomz** [Kitano/KitanoConnectionBundle#21]
Actuellement on ne peut pas détruire une connection entre deux NodeInterface à l'aide de disconnect().

Il faut d'abord récupérer toutes les connections d'une node, puis iterer sur la collection pour voir si notre deuxieme node est présente, puis enfin détruire la connection.

Je pense qu'on pourrait conserver la notion de destruction d'une connection dans une méthode `destroyConnection(ConnectionInterface $connection);` et modifier disconnect() vers 

```
public function disconnect(NodeInterface $souce, NodeInterface $destination);
```

**Comment by armetiz** [comment]
Pas faux,
Et puis avoir le prototype suivant pour disconnect

``` php
public function disconnect(NodeInterface $souce, NodeInterface $destination);
```

C'est plus cohérent vis-à-vis de la méthode connect.

Du coups, je suis pour cette modification :+1: 

Au niveau de destroyConnection, pourquoi ne pas directement faire destroy() ?
Si on modifie disconnect, l'ensemble des méthodes du Manager s'appliquera avec des NodeInterface en entrée.. Du coups, cela peut justifier d'appeler destroyConnection afin de contextualisé l'utilisation de cette méthode..
Maintenant, au niveau perso, je prefere destroy.. :palm_tree: 

@benjamindulau ?

**Comment by benjamindulau** [comment]
:+1: pour l'idée générale
et :+1: pour le `destroy` tout simple ;-)

On pourrait aussi ajouter une option dans la méthode `disconnect` pour `destroy` les connections automatiquement suite au disconnect.

``` PHP
public function disconnect(NodeInterface $souce, NodeInterface $destination, $destroyConnection = false);
```

**Comment by choomz** [comment]
Ok vendu, cool ! Par contre pour le $destroyConnection, je ne sais pas si c'est utile, car l'idée derriere c'est effectivement de détruire la connection, avec ou sans parametre :)

**Comment by armetiz** [comment]
@benjamindulau on avait décidé de ne plus conserver l'état d'une connexion.
Quand on déconnecter deux objets, on détruit la connexion.

**Comment by benjamindulau** [comment]
Ok ! :)
