### ISSUE TITLE
Sens des connections

### ISSUE THREAD

**Issue by choomz** [Kitano/KitanoConnectionBundle#22]
Suite à mes derniers commits, je me rends compte que le sens des connections est exprimé partout dans les méthodes de tests et de récupération, du coup j'ai deux interrogations : 
- isConnectedTo & areConnected font la même chose actuellement
- getConnections est il réellement utile ?

Pour getConnections, j'ai un peu de mal à me projeter dans l'usage. Quel serait l'interet de récupérer l'ensemble des connections dans les deux sens pour un objet ?

Forcer un sens pour toutes les méthodes des connections (source / destination) est à mon avis le meilleur moyen de simplifier l'usage.

Vos avis ?

**Comment by armetiz** [comment]
isConnectedTo tient compte de l'orientation des connections contrairement à areConnected qui cherche si deux objets sont connectés quelque soit l'orientation de cette connection.

getConnections dans la pratique n'a pas forcement d'usage.. Mais vu le cout de cette fonction.. J'aurai tendance à la conserver.

Je ne comprends pas bien comment peux se traduire ta proposition "forcer un sens pour toutes les méthodes..". Si cela signifie ajouter dans les prototypes $source, $destination.. Perso je suis contre, car on va se retrouve avec des appels de méthodes $getConnections(null, $user).. Et le "null" dans une méthode je n'en suis pas fan.

**Comment by choomz** [comment]
Ok alors, actuellement areConnected ne tiens pas compte de l'orientation
https://github.com/Kitano/KitanoConnectionBundle/issues/21

Si on se base sur la signature, pour moi $source & $destination impliquent une orientation. Sinon on signe la méthode avec $node1 et $node2.

Et je ne comprend pas bien pourquoi on se retrouverait avec getConnections(null, $user), pour moi getConnections est à supprimer du connection manager si on force le sens.

Le sens est déduit de $source & $destination, c'est tout.

**Comment by armetiz** [comment]
isConnectedTo : tient compte de l'orientation
areConnected : ne tient pas compte de l'orientation

Les tests unitaires mettent en évidence ce fonctionnement normalement : https://github.com/Kitano/KitanoConnectionBundle/blob/master/Tests/Manager/ConnectionManagerTest.php#L196

Ok pour le changement de signature avec $nodeA, $nodeB quand on ne tient pas compte de l'orientation.

Et pour le getConnections.. Je ne comprends pas où tu voulais en venir.. J'ai donc pris un exemple, mais surement pas le b on.

**Comment by choomz** [comment]
Désolé mais non :) 

https://github.com/Kitano/KitanoConnectionBundle/blob/master/Repository/DoctrineOrmConnectionRepository.php#L151

Je me suis basé sur tes tests unitaires justement pour construire la méthode du repo.

Actuellement les tests passent et areConnected tiens compte du sens. C'est justement ce qui m'a induit en erreur, et c'est pour ça que je l'ai codé comme ça.

**Comment by armetiz** [comment]
Ah ba c'est les Tests qui sont mal écrit alors.

**Comment by armetiz** [comment]
Mise à jour de areConnected test & des prototypes areConnected : nodeA & nodeB remplacent source & destination

https://github.com/Kitano/KitanoConnectionBundle/commit/592440c0a97af916d6e8c8cb6963e16a659761c5
https://github.com/Kitano/KitanoConnectionBundle/commit/dca677cdebec27b4855e225c9f773091ae2f0455

**Comment by benjamindulau** [comment]
La méthode `getConnections` est simplement un raccourci pour faire `getConnectionsTo` + `getConnectionsFrom`.

Il y a des cas d'utilisation (mais avec un super cache).
On peut imaginer afficher de l'auto-complétion dans un champs de recherche avec une liste d'utilisateurs avec qui un autre utilisateur est connecté, classique.

Dans ce cas pas de secret, il faut sérialiser l'ensemble des connections, et les conserver à jour dans un cache par ex.

C'est un cas d'utilisation, mais je pense qu'il y en a d'autres.
Par exemple, pour la mise à jour de fil d'actu, si un utilisateur fait une action, je veux récupérer toutes ses connections pour déclencher la mise à jour de leur fil d'actu.

**Comment by armetiz** [comment]
C'est plus cohérent maintenant.
