### ISSUE TITLE
Type des connections

### ISSUE THREAD

**Issue by choomz** [Kitano/KitanoConnectionBundle#23]
Actuellement on permet la création de connections non typées. Selon moi une connection devrait forcément avoir un type, je me vois mal utiliser une connection sans la qualifier.

Rendre le typage des connections obligatoire simplifierai grandement la gestion de la déconnection de deux nodes : 
https://github.com/Kitano/KitanoConnectionBundle/blob/master/Manager/ConnectionManager.php#L226

Ici par exemple, si on ne passe pas de type pour la déconnection, on peut potentiellement se retrouver avec plusieurs connections à supprimer.

C'est fonctionnel actuellement, mais c'est toujours dans un soucis de simplification.

Vos avis ?

**Comment by armetiz** [comment]
Je ne comprends pas, une connexion a forcement un type "like", "follow" ? C'est d'ailleurs vérifié dans le FilterValidator, et c'est une contraire Doctrine.

**Comment by choomz** [comment]
Effectivement pour la création, mais par pour la deconnection.

Est ce que c'est voulu de pouvoir déconnecter toutes les connections entre deux nodes ? ou doit on typer obligatoirement la deconnection également ? cf mon précédent lien.

**Comment by armetiz** [comment]
Si à mon avis quelque chose qui n'a pas été réfléchit.
Mais là normalement ce n'est pas possible de détruire des connections sans spécifier le 'type'. Car c'est vérifié par le FilterValidator.

D'ailleurs, ca pose la question de pouvoir utiliser getConnectionsXXX sans spécifier de 'type'. Le FilterValidator va nous gener ici.

**Comment by choomz** [comment]
Ben actuellement ça passe. Il y a eu des regressions dans le validateur lors du refactoring je crois.

**Comment by benjamindulau** [comment]
:+1: faudrait pouvoir supprimer seulement certaines connections entre utilisateurs.

Ça serait cool de pouvoir passer un array de "type" à supprimer d'ailleurs non ?

**Comment by choomz** [comment]
Pour le filter validator, si on veut forcer un type, il ne faudrait pas supprimer le = array() dans la signature du manager ?

Ensuite, pour ce qui est du passage array / string de certains paramètres, il me semble que la 1ere version du validateur gérait une transformation. 

A vérifier mais il faudrait boucler la question sur la validation & le passage des filtres non ?

**Comment by armetiz** [comment]
Suite à une discussion sur IRC.
Nous pensons qu'il est interessant de supprimer la notion de "filtre" et de n'avoir que la notion de "type" sur l'ensemble des prototypes liés à la gestion des connexions.

Voici un cas d'utilisation :
$cm->getConnectionsFrom($user, array('like', 'share')); //Les connexions d'un utilisateur avec le type : like & share
$cm->getConnectionsFrom($user, array('like')); //Les connexions d'un utilisateur avec le type : like
$cm->getConnectionsFrom($user); //Les connexions d'un utilisateur quelque soit le type

Mon vote : :+1:

**Comment by choomz** [comment]
:+1:

**Comment by armetiz** [comment]
@benjamindulau vote :-1: 
Anyway, on garde les options comme telle.

**Comment by choomz** [comment]
:+1:
