### ISSUE TITLE
ConnectionCommand

### ISSUE THREAD

**Issue by armetiz** [Kitano/KitanoConnectionBundle#24]
Quel intérêt d'avoir deux méthodes addConnectCommand & addDisconnectCommand qui ont le meme body ? addCommand doit être suffisant non ?

Je pense qu'il est préférable de ne pas utiliser 'connections' comme nom de propriété mais plutôt 'commands' afin d'éviter les confusions avec les Connection.

**Comment by choomz** [comment]
Oui alors là j'ai fais l'objet rapidos, effectivement on peut modifier la terminologie.

Ensuite pour les deux, non ce n'est pas la meme chose, il y en a un qui prend un type en string et l'autre un filters en array.

**Comment by armetiz** [comment]
https://github.com/Kitano/KitanoConnectionBundle/commit/029cdf16da832e624af26ec9aa7cde9c4619a912
