### ISSUE TITLE
Is ConnectionManager::deconnection() method is really needed ?

### ISSUE THREAD

**Issue by armetiz** [Kitano/KitanoConnectionBundle#7]
Que signifie "dé-connection" ? Car au final, si on dé-connect une Connection, comment on fait pour la retrouver ? Doit-on mettre dans les filtres des méthodes ConnectionManagerInterface l'état de la connexion ?

**Comment by benjamindulau** [comment]
I think it is needed because we would be able to know that two objets were connected at some point.
