### ISSUE TITLE
Utilisation d'un Listener ou du Manager pour remplir Model/Connection 

### ISSUE THREAD

**Issue by armetiz** [Kitano/KitanoConnectionBundle#8]
Doit-on charger automatiquement les Connection::source & destination de maniere automatique via un Listener Doctrine ? 
Dans ce cas, il en faut un pour ORM, ODM etc..

**Comment by choomz** [comment]
Je pense qu'il faut gérer les deux ORM / ODM, c'est une couche en plus certes, mais si on part dans la navigation de type graph en excluant mongo dès le départ, ça risque d'être frustrant.

D'autant plus que Doctrine le gère (et oui nous serions couplé à doctrine).

**Comment by armetiz** [comment]
Yes exactement. Mais surtout, je pense qu'il faut pouvoir gérer aussi des solutions plus adaptées : Neo4J. 

D'ailleurs, est-ce que l'on doit pouvoir faire une Connection entre un model User géré via RDBMS, et un Book géré via NoSQL ? QUID MongoDB, CouchDB & surtout Neo4J.

**Comment by choomz** [comment]
Je pense que pour une v1, il ne faut pas s'arracher les cheveux avec de la compatibilité inter système.
Par contre une implémentation du pattern adapter avec au démarage Interface + adapter doctrine orm + doctrine odm mongo db me semble nécessaire.

Pour ce qui est de Neo4J, même si en terme de modelisation c'est le plus adapté rapport au bundle, je ne suis pas sur que la gestion des connections se fasse avec notre approche ... si quelqu'un pouvait confirmer ou infirmer ?

**Comment by benjamindulau** [comment]
Je trouve que l'utilisation du Listener n'est pas trop approprié.
IMHO, c'est le repository, puisque que c'est lui l'implementation concrète du système de persistance, qui devrait transformer l'objet avant de le retourner.

On aura donc une interface pour le repo, et une seule classe à implémenter pour chaque système de persistance, ORM, ODM, propel, ou autre.

**Comment by armetiz** [comment]
Dans ce cas, cela signifie que l'on ne peux lier que des objets appartenant au meme système de persistance.
Car un Repository est lié à système.. Si c'est lui qui gere la transformation de la Connection, il ne va pouvoir récupérer des objets appartenant uniquement au meme système.

De mon coté, je ne pense pas avoir besoin d'utiliser un RDBMS + un NoSQL pour stocker mes Models.. 

Il peut-être interessant de définir le besoin pour répondre à la question.

PS : Je pense que le Listener est en effet inapproprié. Par contre, je pense que cela doit être initié par le Manager et non par le Repository qui gere la Connection.

**Comment by armetiz** [comment]
Actuellement c'est le Repository qui est en charge de remplir les Connection.
