### ISSUE TITLE
Prototype de ConnectionManagerInterface getConnectionsXX

### ISSUE THREAD

**Issue by armetiz** [Kitano/KitanoConnectionBundle#9]
Au niveau des méthodes getConnectionsXX. On utilise les filtres de cette manière ?

``` php
$filters = array (
  'status' => Connection::CONNECTED,
  'type' => array(like', 'follow'),
);
```

L'interface 

``` php
public function getConnections(NodeInterface $value, array $filters = array());
```

Ou alors 

``` php
$filters = array (
  'status' => Connection::CONNECTED,
);

$types = array(like', 'follow'),
```

L'interface 

``` php
public function getConnections(NodeInterface $value, array types = array(), array $filters = array());
```

**Comment by armetiz** [comment]
J'ai refactorisé la branch master sur ce point.
Maintenant il n'y a que le paramètre 'filters'.

L'objectif est d'utiliser 'filters' pour spécifier les 'type', les 'status' et la profondeur des connections que l'on souhaite obtenir. En utilisant un système d'option par défaut, on peux spécifier que 'status' est par défaut égale à Connection::CONNECTED, et deep à 1.
Qu'en penses-vous ? https://github.com/Kitano/KitanoConnectionBundle/blob/master/Manager/ConnectionManagerInterface.php

**Comment by benjamindulau** [comment]
Concernant les filtres il y a 2 écoles, soit un objet spécifique mais c'est un peu lourd, soit une validation à la mano d'un  tableau qui est passé en brut.

Dans le cas d'un tableau brut, nous aurions éventuellement une liste de "allowed_filters" dans le manager, et un petit nettoyage des clés passées dans le tableau. Ensuite soit nous ignorons toutes les autres valeurs, soit nous sommes plus strictes et nous levons une exception quand un filtre n'est pas autorisé.

**Comment by benjamindulau** [comment]
J'ajoute que nous pouvons aussi avoir des valeurs par défaut pour les filtres et faire un merge de ces valeurs avec les valeurs de l'utilisateur.

**Comment by choomz** [comment]
Je viens de pousser un début d’implémentation de la validation des filtres, mais ça soulève des questions par rapport à ce que tu dis @benjamindulau  : 

https://github.com/Kitano/KitanoConnectionBundle/blob/filters/Manager/ConnectionManager.php#L179
- Si $allowedFilters correspond aux filtres que les connections peuvent gérer et aux paramètres nécessaires au bon fonctionnement interne, alors 'type' peut être potentiellement n'importe quoi, puisque c'est au développeur de typer ses connections (like, tag, poke, whatever ..). Je propose un test un peu naîf sur un string NotNull ..
- Il y a donc également un exemple générique basé sur la connection status, le validateur teste juste l'existence des potentielles valeurs attendues, on peut ensuite valider comme ceci n'importe quoi.
- Actuellement le $allowedFilers est un tableau statique, on pourrait imaginer une propriété $filters du connection manager qui recevrait un tableau du container, ou d'ailleurs. Doit on pouvoir spécifier les valeurs par défault des autres filtres depuis la conf ? D'ailleurs quels pourraient être ces futurs paramètres ?

EDIT : la profondeur en fait également partie, je pense qu'il faudrait quand même extraire une liste des possibilités pour ce tableau. 

J'ai donc mis 3 types de validation : allowed_values / constraints / default

Bref qu'en pensez vous ?

Re EDIT : On pourrait aussi imaginer un validateur que l'on gere en annotations sur la class qui implémente NodeInterface et qui prend les parametres les filtres lorsque l'on veut les connections pour cette Node ...
